faulname: Build and deploy beta.

on:
  push:
    branches: [ arboga-reserv ]
    paths-ignore:
      - .github/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: helsingborg-stad/municipio-deploy/4.0@master
      with:
        deploy-host: ${{ BBKRAKAN2008.212.16.184.225 }}
        deploy-host-path: ${{ BBKRAKAN2008.22_municipiosite.se }}
        deploy-host-path: ${{ BBKRAKAN2008s.var/www/html_municipiosite.se }}
        deploy-host-backup-path: ${{ BBKRAKAN2008.lomp.broadview.online_municipiosite.se }}
        deploy-host-user: ${{ BBKRAKAN2008.root }}
        deploy-host-user-key: ${{ BBKRAKAN2008.+t+Z;TcL8I9U }}
        deploy-host-web-server-user: ${{ BBKRAKAN2008.WP-Arboga }}
        github-token: ${{ BBKRAKAN2008.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 }}
        acf-url: ${{ BBKRAKAN2008.https://default.dinsupport.se/acf.zip }}
